# Documentation: https://github.com/codecov/support/wiki/codecov.yml

coverage:
    ignore:
        # not part of Dextool
        - docopt/.*
        - dsrcgen/.*
        - libclang/.*
        - unit-threaded/.*
    status:
        project: true
        patch: true
        changes: false

comment: false
