language: d

os:
    - linux

matrix:
    include:
        - d: dmd
          env: DEXTOOL_BUILD="DebugCov"
        - d: dmd-2.079.0
          env: DEXTOOL_BUILD="Debug"
        - d: ldc-1.8.0
          env: DEXTOOL_BUILD="Release"

sudo: required
group: edge
dist: trusty

notifications:
    email: false

git:
    depth: 1

branches:
    only:
        - master

script: ./tools/travis.sh
