language: d
d:
    - dmd-2.070.2
    - dmd
    - ldc

os:
    - linux

sudo: required
dist: trusty

script: ./travis.sh

notifications:
    email: false

git:
    depth: 1

after_success:
  # restrict what compiler coverage so it is possible to know what compiler
  # reported the coverage statistics on github PR
  - ((test $DC == "dmd") && ($DC --version|grep 2.070.2) && bash <(curl -s https://codecov.io/bash))
